CXXFLAGS=--std=c++0x -g -O2 -Wall
LD=g++
CC=g++


cassis_cli: GameState.o cassis_cli.o

bruteforce: GameState.o bruteforce.o


clean:
	-rm *.o
	-rm cassis_cli
	rm *~

depend:
	makedepend *.cpp *.hpp -Y .
# DO NOT DELETE

cassis_cli.o: GameState.hpp /usr/include/assert.h /usr/include/features.h
cassis_cli.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
cassis_cli.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
cassis_cli.o: /usr/include/gnu/stubs-64.h
cassis_gtk_cairo.o: /usr/include/math.h /usr/include/features.h
cassis_gtk_cairo.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
cassis_gtk_cairo.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
cassis_gtk_cairo.o: /usr/include/gnu/stubs-64.h /usr/include/bits/huge_val.h
cassis_gtk_cairo.o: /usr/include/bits/huge_valf.h
cassis_gtk_cairo.o: /usr/include/bits/huge_vall.h /usr/include/bits/inf.h
cassis_gtk_cairo.o: /usr/include/bits/nan.h /usr/include/bits/mathdef.h
cassis_gtk_cairo.o: /usr/include/bits/mathcalls.h GameState.hpp IA.hpp
cassis_gtk_cairo.o: cassis_cairo.hpp cairo_graphic_controller.hpp
cassis_gtk_cairo.o: SpriteCollection_cairo.hpp /usr/include/assert.h
cassis_gtk_cairo.o: cairo_menu_selector.hpp cairo_text_display.hpp
cassis_gtk_cairo.o: /usr/include/string.h /usr/include/xlocale.h
GameState.o: GameState.hpp
IA.o: IA.hpp GameState.hpp /usr/include/stdlib.h /usr/include/features.h
IA.o: /usr/include/bits/predefs.h /usr/include/sys/cdefs.h
IA.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
IA.o: /usr/include/gnu/stubs-64.h /usr/include/sys/types.h
IA.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
IA.o: /usr/include/time.h /usr/include/endian.h /usr/include/bits/endian.h
IA.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
IA.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
IA.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
IA.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SpriteCollection_cairo.o: /usr/include/stdlib.h /usr/include/features.h
SpriteCollection_cairo.o: /usr/include/bits/predefs.h
SpriteCollection_cairo.o: /usr/include/sys/cdefs.h
SpriteCollection_cairo.o: /usr/include/bits/wordsize.h
SpriteCollection_cairo.o: /usr/include/gnu/stubs.h
SpriteCollection_cairo.o: /usr/include/gnu/stubs-64.h
SpriteCollection_cairo.o: /usr/include/sys/types.h /usr/include/bits/types.h
SpriteCollection_cairo.o: /usr/include/bits/typesizes.h /usr/include/time.h
SpriteCollection_cairo.o: /usr/include/endian.h /usr/include/bits/endian.h
SpriteCollection_cairo.o: /usr/include/bits/byteswap.h
SpriteCollection_cairo.o: /usr/include/sys/select.h
SpriteCollection_cairo.o: /usr/include/bits/select.h
SpriteCollection_cairo.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
SpriteCollection_cairo.o: /usr/include/sys/sysmacros.h
SpriteCollection_cairo.o: /usr/include/bits/pthreadtypes.h
SpriteCollection_cairo.o: /usr/include/alloca.h SpriteCollection_cairo.hpp
SpriteCollection_cairo.o: /usr/include/assert.h
cairo_menu_selector.o: cassis_cairo.hpp GameState.hpp IA.hpp
cairo_menu_selector.o: cairo_graphic_controller.hpp
cairo_menu_selector.o: SpriteCollection_cairo.hpp /usr/include/assert.h
cairo_menu_selector.o: /usr/include/features.h /usr/include/bits/predefs.h
cairo_menu_selector.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
cairo_menu_selector.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-64.h
cairo_menu_selector.o: cairo_text_display.hpp /usr/include/string.h
cairo_menu_selector.o: /usr/include/xlocale.h
cairo_text_display.o: cairo_graphic_controller.hpp /usr/include/string.h
cairo_text_display.o: /usr/include/features.h /usr/include/bits/predefs.h
cairo_text_display.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
cairo_text_display.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-64.h
cairo_text_display.o: /usr/include/xlocale.h
cassis_cairo.o: GameState.hpp IA.hpp cairo_graphic_controller.hpp
cassis_cairo.o: SpriteCollection_cairo.hpp /usr/include/assert.h
cassis_cairo.o: /usr/include/features.h /usr/include/bits/predefs.h
cassis_cairo.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
cassis_cairo.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-64.h
IA.o: GameState.hpp
SpriteCollection_cairo.o: /usr/include/assert.h /usr/include/features.h
SpriteCollection_cairo.o: /usr/include/bits/predefs.h
SpriteCollection_cairo.o: /usr/include/sys/cdefs.h
SpriteCollection_cairo.o: /usr/include/bits/wordsize.h
SpriteCollection_cairo.o: /usr/include/gnu/stubs.h
SpriteCollection_cairo.o: /usr/include/gnu/stubs-64.h
